<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLzLvV1b\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLzLvV1b/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLzLvV1b.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLzLvV1b\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLzLvV1b\App_KernelDevDebugContainer([
    'container.build_hash' => 'LzLvV1b',
    'container.build_id' => '7221f2b0',
    'container.build_time' => 1666367484,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLzLvV1b');
